version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    labels:
      - com.centurylinklabs.watchtower.scope=infrastructure
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SERVERURL: "vpn.barnes.biz"
      SERVERPORT: 51820
      PEERS: 4
      PEERDNS: 8.8.8.8
      INTERNAL_SUBNET: 10.13.13.0
      VIRTUAL_HOST: vpn.barnes.biz
      VIRTUAL_PORT: 51820
      LETSENCRYPT_HOST: vpn.barnes.biz
      LETSENCRYPT_EMAIL: christopher@barnes.biz
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - internet

networks:
  internet:
    external: true