---
kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.42.0.0/16"
    clusterPoolIPv4MaskSize: 24

routingMode: native
ipv4NativeRoutingCIDR: "10.42.0.0/16"
autoDirectNodeRoutes: true

loadBalancer:
  enabled: true
  mode: dsr
  acceleration: disabled

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

bpf:
  masquerade: true
