---
alertmanager:
  enabled: true

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 200m
        memory: 400Mi

    retention: 10d
    service:
      type: ClusterIP

    serviceMonitorSelectorNilUsesHelmValues: false
