version: '3.8'
services:
  minecraft:
    image: itzg/minecraft-server:java21-graalvm
    container_name: minecraft
    environment:
      TYPE: PAPER
      PAPERBUILD: 138
      EULA: "true"
      INIT_MEMORY: 512M
      MAX_MEMORY: 3G
      MAX_PLAYERS: 6
      MAX_TICK_TIME: -1
      SNOOPER_ENABLED: "false"
      VIEW_DISTANCE: 20
      ENABLE_RCON: "true"
      RCON_PORT: 25575
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_CMDS_STARTUP:  |-
        chunky radius 1000
        chunky start
        chunky continue
      RCON_CMDS_FIRST_CONNECT: |-
        chunky pause
      RCON_CMDS_LAST_DISCONNECT: |-
        chunky continue
    ports:
      - "25565:25565" # Server
      - "25575:25575" # RCON
    volumes:
      - minecraft_data:/data
      - ./plugins:/plugins
    restart: unless-stopped
    networks:
      monitoring:
      minecraft:

volumes:
  minecraft_data:
    name: minecraft_data

networks:
  monitoring:
    external: true
  minecraft:
    name: minecraft
    driver: bridge