version: '3.8'
services:
  minecraft:
    image: itzg/minecraft-server:java21-graalvm
    container_name: minecraft
    environment:
      TYPE: PAPER
      PAPERBUILD: 138
      EULA: "true"
      MEMORY: 3G
      MAX_PLAYERS: 6
      MAX_TICK_TIME: -1
      SNOOPER_ENABLED: "false"
      VIEW_DISTANCE: 20
      ENABLE_RCON: "true"
      RCON_PORT: 25575
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_CMDS_STARTUP:  |-
        chunky radius 1000
        chunky start
        chunky continue
      RCON_CMDS_FIRST_CONNECT: |-
        chunky pause
      RCON_CMDS_LAST_DISCONNECT: |-
        chunky continue
    ports:
      - "25565:25565" 
      - "8123:8123"
      - "25575:25575"
    volumes:
      - minecraft_data:/data
      - ./plugins:/plugins
    restart: unless-stopped
    networks:
      - minecraft

  minecraft-prometheus-exporter:
    image: ghcr.io/dirien/minecraft-exporter
    container_name: minecraft-prometheus-exporter
    environment:
      MC_RCON_HOST: minecraft
      MC_RCON_PORT: 25575
      MC_RCON_PASSWORD: ${RCON_PASSWORD}
    command: 
    - '--log.level=info'
    ports:
      - "9150:9150"
    networks:
      - minecraft
    depends_on:
      - minecraft
    

volumes:
  minecraft_data:
    name: minecraft_data

networks:
  minecraft:
    name: minecraft
    driver: bridge