---
alertmanager:
  enabled: true

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 10d
    resources:
      requests:
        memory: 400Mi
        cpu: 200m

    service:
      type: ClusterIP
