---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: cert-manager
  namespace: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: core
  source:
    helm:
      valueFiles:
        - values.yaml
    path: argocd/core/charts/cert-manager
    repoURL: https://github.com/barnes-c/cluster
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
