---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: core
  source:
    repoURL: https://github.com/barnes-c/cluster
    targetRevision: master
    path: argocd/core/charts/cert-manager
    helm:
      valueFiles:
        - values.yaml 
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
