---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  name: longhorn
  namespace: longhorn-system
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: core
  source:
    helm:
      valueFiles:
        - values.yaml
    path: argocd/core/charts/longhorn
    repoURL: https://github.com/barnes-c/cluster
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
