---
image:
  tag: v1.119.0

useDeprecatedPostgresChart: true

immich:
  metrics:
    enabled: false
  configuration:
    storageTemplate:
      enabled: true
      template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
  persistence:
    library:
      existingClaim: immich-library

postgresql:
  enabled: true
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
  global:
    postgresql:
      auth:
        username: immich
        password: immichpass
        database: immich
  primary:
    persistence:
      enabled: true
      size: 512Mi
      storageClass: longhorn
    containerSecurityContext:
      readOnlyRootFilesystem: false
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 256Mi
      storageClass: longhorn

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  env:
    DB_HOSTNAME: immich-postgresql
    DB_USERNAME: immich
    DB_DATABASE_NAME: immich
    DB_PASSWORD: immichpass
    REDIS_HOSTNAME: immich-redis-master
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: img.barnes.biz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - img.barnes.biz
          secretName: img.barnes.biz-tls

machine-learning:
  enabled: false
