version: '3.8'
services:
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./barnes.biz.conf:/etc/nginx/conf.d/default.conf
      - ./snippets:/etc/nginx/snippets
      - ./certs:/etc/nginx/certs
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-logs:/var/log/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email Christopher@Barnes.biz --agree-tos --no-eff-email -d barnes.biz www.barnes.biz
