immich:
  uploadLocation: s3
  s3:
    endpoint: minio.minio.svc.cluster.local:9000
    bucket: immich
    region: eu-west-1
    accessKey: minioadmin
    secretKey: minioadmin123
    useHttps: false
    forcePathStyle: true

  machine-learning:
    enabled: false

  server:
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: img.barnes.biz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - img.barnes.biz
            secretName: img.barnes.biz-tls

  redis:
    enabled: true
    architecture: standalone
    master:
      resources:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 128Mi
          cpu: 100m

  postgres:
    enabled: true
    auth:
      username: immich
      password: immichpass
      database: immich
