---
apiVersion: v1
data:
  redirect.conf: |
    server {
        listen 80;
        server_name _;
        return 301 https://github.com/barnes-c;
    }
kind: ConfigMap
metadata:
  name: website-redirect
  namespace: website
