---
global:
  domain: argo.barnes.biz
server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    enabled: true
    hosts:
      - argo.barnes.biz
    ingressClassName: nginx
    tls:
      - hosts:
          - argo.barnes.biz
        secretName: argocd-tls
  service:
    type: ClusterIP
  extraArgs:
    - --insecure
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 125m
      memory: 256Mi
configs:
  cm:
    application.instanceLabelKey: argo.argoproj.io/instance
    timeout.reconciliation: 180s
  rbac:
    policy.csv: |
      g, system:authenticated, role:admin
    policy.default: role:readonly
  secret:
    createSecret: true
controller:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 125m
      memory: 256Mi
repoServer:
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 125m
      memory: 256Mi
applicationSet:
  enabled: true
dex:
  enabled: true
redis:
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
