- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Create user and add to docker and sudo groups
  user:
    name: "{{ user_name }}"
    groups: "docker,sudo"
    append: true
    shell: /bin/bash
    create_home: true

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"

- name: Add authorized SSH key
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ ssh_key }}"

- name: Create sudoers file for passwordless sudo
  copy:
    dest: "/etc/sudoers.d/{{ user_name }}"
    content: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL\n"
    owner: root
    group: root
    mode: "0440"
  notify: Validate sudoers
