---
- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
  retries: 5
  delay: 10
  register: result
  until: result is succeeded

- name: Install docker-compose
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: docker
    append: true
