---
grafana:
  adminPassword: changeme

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          access: proxy
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
        - name: Prometheus
          access: proxy
          isDefault: true
          type: prometheus
          url: http://prometheus-operated.monitoring.svc.cluster.local:9090

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
      - monitoring.barnes.biz
    ingressClassName: traefik
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts:
          - monitoring.barnes.biz
        secretName: monitoring-tls
