apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ipv6nat-claim
  name: ipv6nat-claim
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
