---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: argocd/apps/charts/monitoring/*
        repoURL: https://github.com/barnes-c/cluster
        revision: HEAD
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: monitoring
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          valueFiles:
            - values.yaml
        path: argocd/apps/charts/monitoring/{{path.basename}}
        repoURL: https://github.com/barnes-c/cluster
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
