apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/barnes-c/cluster
    targetRevision: master
    path: apps/immich
    helm:
      chart: immich
      repoURL: https://immich-app.github.io/immich-charts
      targetRevision: 0.9.3
      valueFiles:
        - values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
