apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  generators:
    - directory:
        configMapRef: repo-root
        directory: apps/monitoring
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/barnes-c/cluster
        targetRevision: HEAD
        path: apps/monitoring/{{path.basename}}
        helm:
          valueFiles:
            - values.yaml
        chart: '{{path.basename}}'
        repoURL: '{{repo_url}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
  templateParameters:
    - name: repo_url
      values:
        grafana: https://grafana.github.io/helm-charts
        prometheus: https://prometheus-community.github.io/helm-charts
        loki: https://grafana.github.io/helm-charts
        fluent-bit: https://fluent.github.io/helm-charts
