apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  generators:
    - directory:
        configMapRef: monitoring-root
        directory: apps/charts/monitoring
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/barnes-c/cluster
        targetRevision: HEAD
        path: apps/monitoring/{{path.basename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
