---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/barnes-c/cluster
    targetRevision: HEAD
    path: apps/wireguard
    helm:
      chart: pod-gateway
      repoURL: https://angelnu.github.io/helm-charts
      version: 6.5.1
      valueFiles:
        - values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: wireguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
