---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://angelnu.github.io/helm-charts
    chart: pod-gateway
    targetRevision: 6.5.1
    helm:
      valueFiles:
        - apps/wireguard/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: wireguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
