---
mode: standalone

auth:
  rootUser: minioadmin
  rootPassword: minioadmin123

persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi

ingress:
  enabled: true
  hostname: s3.barnes.biz
  ingressClassName: traefik
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

provisioning:
  enabled: true
  buckets:
    - name: default
      policy: none
