---
mode: standalone
persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi
auth:
  rootUser: minioadmin
  rootPassword: minioadmin123
ingress:
  enabled: true
  hostname: s3.barnes.biz
  ingressClassName: traefik
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
provisioning:
  enabled: true
  buckets:
    - name: default
      policy: none
  networkPolicy:
    enabled: true
    ingress:
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: minio
  cleanupAfterFinished:
    enabled: false
