---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: eugenmayer/docker-redirect
          env:
            - name: REDIRECT_TARGET
              value: "https://github.com/barnes-c"
          ports:
            - containerPort: 80
