---
modules:
  custom_https:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      preferred_ip_protocol: ip4

  custom_tcp:
    prober: tcp
    timeout: 5s
    tcp:
      ip_protocol_fallback: true
