version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    labels:
      - com.centurylinklabs.watchtower.scope=infrastructure
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
      - com.centurylinklabs.watchtower.scope=infrastructure
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: "https://monitoring.barnes.biz"
      GF_SERVER_DOMAIN: "monitoring.barnes.biz"
      VIRTUAL_HOST: monitoring.barnes.biz
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: monitoring.barnes.biz
      LETSENCRYPT_EMAIL: christopher@barnes.biz
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/conf/custom.ini:/etc/grafana/conf/grafana.ini:ro
    networks:
      monitoring:
      internet:
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    labels:
      - com.centurylinklabs.watchtower.scope=infrastructure
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitoring
    depends_on:
      - prometheus 

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: prometheus-nginx-exporter
    labels:
      - com.centurylinklabs.watchtower.scope=infrastructure
    restart: always
    command:
      - -nginx.scrape-uri=http://nginx-proxy:8080/stub_status
    ports: 
      - "9113:9113"
    networks:
      - monitoring
    depends_on:
      - prometheus   

  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest 
    container_name: cadvisor 
    labels:
      - com.centurylinklabs.watchtower.scope=infrastructure
    ports: 
      - 8081:8080 
    networks: 
      - monitoring 
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
    depends_on: 
      - redis 

  redis: 
    image: redis:latest 
    container_name: redis 
    ports: 
      - 6379:6379 
    networks: 
      - monitoring

networks:
  monitoring:
    name: monitoring
  internet:
    external: true

volumes:
  prometheus_data: {}
  grafana_data: {}
