global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'monitoring.barnes.biz'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx-prometheus-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'nextcloud-prometheus-exporter'
    static_configs:
      - targets: ['nextcloud-prometheus-exporter:9205']

  - job_name: 'blackbox-prometheus-exporter'
    metrics_path: /probe
    params:
      module: [custom_https]  
    scrape_interval: 30s
    static_configs:
      - targets:
        - https://monitoring.barnes.biz
        - https://cloud.barnes.biz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox-prometheus-exporter:9115"

  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['blackbox-prometheus-exporter:9115']

  - job_name: 'watchtower'
    metrics_path: /v1/metrics
    static_configs:
      - targets: ['watchtower:8080']
